// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred2.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Auto1 extends CommandGroup {
    
    public  Auto1() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.
    	
    	addSequential(new HDriveDistance(1,0,0));
    	addSequential(new Debug("DriveForward?"));
    	addParallel(new ToteGrab());
    	addSequential(new Debug("GrabTote?"));
    	
    	addParallel(new Ungrab());
    	addSequential(new Debug("Ungrab?"));
    	
    	addSequential(new Debug("ElevatorUp?"));
    	//addSequential(new Debug("Do I hit this point"));
    	//addSequential(new HDriveDistance(0,0,2*12));
    	//addSequential(new HDriveDistance(3*12,0,0));
    	//addSequential(new HDriveDistance(0,0,-2*12));
    	//addParallel(new ToteGrab());
    	
    	//addSequential(new ToteGrab());
    	
    	
    	//addSequential(new Debug("Drive Done"));
    	 	

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    }
}
